<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.2.4 on 2021-06-09 05:55
=======
# Generated by Django 3.2.3 on 2021-06-06 20:49
>>>>>>> second commit
=======
# Generated by Django 3.2.3 on 2021-06-07 11:58
>>>>>>> second draft for weather api
=======
# Generated by Django 3.2.3 on 2021-06-08 19:29
>>>>>>> I add url path and write unittest for weather api

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('recipe', models.TextField()),
=======
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('city_name', models.CharField(default='Istanbul', max_length=20)),
>>>>>>> second commit
            ],
        ),
    ]
