# Generated by Django 3.2.4 on 2021-06-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Event2',
        ),
    ]
