# Generated by Django 3.2.4 on 2021-06-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_rename_event_event2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('city_name', models.CharField(default='Istanbul', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Event2',
        ),
    ]
